### ISSUE TITLE
Nanopore raw data

### ISSUE THREAD

**Issue by hasindu2008** [marbl/HG002#1]
Is Nanopore raw data available for this?

**Comment by skoren** [comment]
Do you mean the fastq sequences of the fast5 sequences?

**Comment by hasindu2008** [comment]
No, the fast5 files.

**Comment by skoren** [comment]
We did not generate the data in house so never had the fast5 locally. Most of them are available here: https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=NHGRI_UCSC_panel/HG002/nanopore/. The rest are released by ONT: https://labs.epi2me.io/dataindex/ (Sept and Nov 2020 releases) and GIAB: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/HG002_NA24385_son/Ultralong_OxfordNanopore/.

That should cover all of them, I'll add these links to the readme.

**Comment by hasindu2008** [comment]
Thank you very much for the quick response!
