### ISSUE TITLE
Do I have to simulate sequencing from the .fasta before benchmarking?

### ISSUE THREAD

**Issue by lok27395** [marbl/HG002#11]
Hi all,

I am new to the field and I'd like to verify my variant calling pipeline using latest CHM13 as reference. I have the HG002v1.1.fasta here and I got the truth set v1.1.vcf from NIST. 
> (https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/analysis/NIST_HG002_DraftBenchmark_defrabbV0.015-20240215/)

**_Question_**: Do I have to simulate a whole genome reads before mapping (in such case I would use PBSIM3 for the purpose) or I should directly map to CHM13?

My sequencing platform is Pacbio sequel II. My thought is to simulate sequencing errors (closer to the reality) before my variant calling.

Thanks!

**Comment by nhansen** [comment]
Hi! Have you already used your pipeline to create a VCF file using actual HG002 Pacbio reads? If you are comparing your variants to the NIST truth set, you shouldn't need to use HG002v1.1.fasta, since that has already been used by NIST to create their v1.1.vcf. So all you need to do is compare the VCF created by your pipeline using real Pacbio reads to the NIST truth set.

Hope that helps,
--Nancy

**Comment by lok27395** [comment]
> Hi! Have you already used your pipeline to create a VCF file using actual HG002 Pacbio reads? If you are comparing your variants to the NIST truth set, you shouldn't need to use HG002v1.1.fasta, since that has already been used by NIST to create their v1.1.vcf. So all you need to do is compare the VCF created by your pipeline using real Pacbio reads to the NIST truth set.
> 
> Hope that helps, --Nancy

Hi Nancy, thanks you for precious opinions! I've never thought this way. I see your point in "validating" my pipeline and I sure would adopt it.

Btw, is it also logical to proceed in my way? (i.e. simulation) Because our workflow is modified from Pacbio in which we may have limited coverage (may be passes as well) since our samples are limited and we have to amplify before lib. prep.

Thanks!

**Comment by nhansen** [comment]
Maybe I'm not understanding what your pipeline/workflow is doing, then. Is it meant to call variants on PacBio reads? If coverage is an issue, you could always dial back the coverage you use of real reads. In any case, simulating PacBio reads for HG002 will always give you a less accurate representation of what real data will behave like.
