### ISSUE TITLE
HG002 paternal/maternal specific variant

### ISSUE THREAD

**Issue by charliechen912ilovbash** [marbl/HG002#12]
Dear T2T team,
Would you be able to provide the variant list (e.g. .vcf of SNV and small Indel) of:
(1) between HG002 paternal reference and the CHM13 reference, 
(2) between HG002 maternal reference and the CHM13 reference?
I would like to use these parent-specific variants to inspect my phasing result, thanks.

**Comment by nhansen** [comment]
Hi--thanks for the question!

Even though the current HG002 Q100 assembly [HG002v1.1](https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/HG002/assemblies/hg002v1.1.fasta.gz) is highly accurate, the Q100 project hasn't focused on determining the exact variants between it and CHM13.

I'd recommend looking at the [Genome in a Bottle benchmarks](https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/analysis/NIST_HG002_DraftBenchmark_defrabbV0.018-20240716/) which have used the v1.1 Q100 assembly, along with dipcall, to determine CHM13 variants. Although their VCF files are for the entire diploid sample, they are phased, so you should be able to easily parse out the maternal and paternal reference variants from those files.

Hope that helps,
--Nancy

**Comment by nhansen** [comment]
For evaluating the phasing in HG002 assemblies, the [q100bench](https://github.com/nhansen/q100bench) package uses heterozygous sites within HG002v1.1 to calculate switch rates and plot where scaffolds are maternal or paternal. A soon-to-be-released improvement on q100bench called "qualiffy" uses an HMM with kmers unique to the maternal or paternal Q100 benchmark to estimate phase blocks as well. I'll post here when qualiffy is available.

**Comment by charliechen912ilovbash** [comment]
Thank you very much for the rapid reply. I will confirm the GIAB benchmark, and looking forward to the qualiffy!

**Comment by charliechen912ilovbash** [comment]
@nhansen 
I checked the GRCh38 GIAB benchmark (GRCh38_HG2-T2TQ100-V1.1.vcf.gz) but did not see any phase set information, which is usually generated by phasing tools like WhatsHap. 
Does this mean that all the variants are in the same phase set?

**Comment by nhansen** [comment]
Hi again. The GIAB benchmark is created using the Q100 benchmark, which is fully phased (both via Hi-C during assembly, and by polishing). Because it aligns the maternal and paternal haplotypes to GRCh38/CHM13 separately and is created with dipcall/PAV, the benchmark is fully phased without tools like WhatsHap. You can use the genotypes "1|0" and "0|1" to determine if a variant is paternal or maternal only. Hope that helps!

**Comment by charliechen912ilovbash** [comment]
Thank you, I understood. A fully phased reference is really awesome!

**Comment by nhansen** [comment]
Thanks! We think so too! Let me know if you have any further questions.
