### ISSUE TITLE
Truth_set information for benchmarking

### ISSUE THREAD

**Issue by poddarharsh15** [marbl/HG002#8]
Hi,
I'm currently working on benchmarking VCF files generated from HG002_data(test_run just one sample) for SV calling(Manta, lumpy, GRIDSS, nf-core/sarek) against a truth set. I aligned the BAM files using GRCh38. Any ideas on how to effectively benchmark my results on which truth set?
Thank you.

**Comment by nhansen** [comment]
Hi! For SVs, I believe the best current benchmark is the "Genome in a Bottle" datasets maintained by NIST (see the v0.6 SV release here: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/NIST_SV_v0.6/).

We don't currently have a pipeline for benchmarking SV VCFs using our Q100 v1.0 release, but in the future, it should be possible to do this by inferring a genome using your VCFs and the reference sequence, and comparing that against our diploid genome.

Hope that helps! Let us know if you have other questions.

**Comment by poddarharsh15** [comment]
Thank you for answering, I have one confusion can I use the truth_sets from SV_0.6/ for bench the vcf_files(aligned on GRCh38) generated from SV caller tools.
I am using truvari and SVanalyzer for benchmarking.

**Comment by nhansen** [comment]
Sorry for the slow response! As of this date, there are only Genome in a Bottle benchmark SVs against the hg19 (GRCh37) reference.

**Comment by poddarharsh15** [comment]
Hello,

I trust this message finds you well. I've been working on benchmarking my VCF files using HG002 T2T truth files. I aligned my BAM files using three different aligners on GRCh38 genome (bwamem, dragen, minimap) and generated VCF files using five different SV callers (manta, delly, lumpy, nfcore/sarek, dysgu).

Considering this scenario, would you recommend using truvari as the benchmarking tool to obtain comprehensive results for assessing the efficiency of these pipelines? Your guidance on the choice of a benchmarking tool would be immensely valuable.

Thank you for your assistance.
